apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app            # Name of the deployment
spec:
  replicas: 2                # Number of pod replicas
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: [repository-url]:latest  # Docker image from your ECR repository
        ports:
        - containerPort: 5000           # Port the app is running on inside the container
