apiVersion: v1
kind: Service
metadata:
  name: flask-service # Name of the service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the service
      targetPort: 5000 # Port in the container to forward requests to
  type: LoadBalancer # Expose the service externally
